# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box              = "gusztavvargadr/windows-server-2022-standard"
  config.vm.box_check_update = false
  config.vm.hostname         = "win2022"
  config.vm.communicator     = "winssh"

  config.vm.network "private_network", ip: "192.168.56.21"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "windows-server-2022"
    vb.memory = 4096
    vb.cpus   = 2
    vb.gui    = false
  end

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["displayName"] = "windows-server-2022"
    vmware.vmx["memsize"]     = "4096"
    vmware.vmx["numvcpus"]    = "2"
    vmware.gui                = false
  end

  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    Write-Host "Windows Server 2022 ready. IP: 192.168.56.21"
  SHELL
end
