# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box              = "bento/ubuntu-24.04"
  config.vm.box_check_update = false
  config.vm.hostname         = "jenkins"

  config.vm.network "private_network", ip: "192.168.56.80"
  config.vm.network "forwarded_port",  guest: 8080, host: 8084

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "jenkins"
    vb.memory = 3072
    vb.cpus   = 2
    vb.gui    = false
  end

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["displayName"] = "jenkins"
    vmware.vmx["memsize"]     = "3072"
    vmware.vmx["numvcpus"]    = "2"
    vmware.gui                = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -y docker.io
    systemctl enable docker && systemctl start docker

    mkdir -p /opt/jenkins
    chown 1000:1000 /opt/jenkins

    docker run -d \
      --name jenkins \
      --restart unless-stopped \
      -p 8080:8080 \
      -p 50000:50000 \
      -v /opt/jenkins:/var/jenkins_home \
      -v /var/run/docker.sock:/var/run/docker.sock \
      jenkins/jenkins:lts-jdk21

    echo "Jenkins starting (1-2 minutes)..."
    echo "UI: http://192.168.56.80:8080"
    echo ""
    echo "Initial admin password (after startup):"
    echo "  vagrant ssh -c 'sudo cat /opt/jenkins/secrets/initialAdminPassword'"
  SHELL
end
