# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box              = "bento/ubuntu-24.04"
  config.vm.box_check_update = false
  config.vm.hostname         = "k3s"

  config.vm.network "private_network", ip: "192.168.56.43"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "k3s"
    vb.memory = 2048
    vb.cpus   = 2
    vb.gui    = false
  end

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["displayName"] = "k3s"
    vmware.vmx["memsize"]     = "2048"
    vmware.vmx["numvcpus"]    = "2"
    vmware.gui                = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    export INSTALL_K3S_EXEC="--node-ip=192.168.56.43 --flannel-iface=eth1"
    curl -sfL https://get.k3s.io | sh -
    systemctl enable k3s
    # Copy kubeconfig for vagrant user
    mkdir -p /home/vagrant/.kube
    cp /etc/rancher/k3s/k3s.yaml /home/vagrant/.kube/config
    sed -i 's/127.0.0.1/192.168.56.43/' /home/vagrant/.kube/config
    chown -R vagrant:vagrant /home/vagrant/.kube
    echo "k3s ready. kubectl get nodes"
  SHELL
end
