# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box              = "bento/rockylinux-9"
  config.vm.box_check_update = false
  config.vm.hostname         = "rocky9"

  config.vm.network "private_network", ip: "192.168.56.11"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "rocky-linux-9"
    vb.memory = 1024
    vb.cpus   = 1
    vb.gui    = false
  end

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["displayName"] = "rocky-linux-9"
    vmware.vmx["memsize"]     = "1024"
    vmware.vmx["numvcpus"]    = "1"
    vmware.gui                = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    dnf update -y -q
    dnf install -y curl git vim htop net-tools
    echo "Rocky Linux 9 ready. IP: 192.168.56.11"
  SHELL
end
