# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box              = "bento/ubuntu-24.04"
  config.vm.box_check_update = false
  config.vm.hostname         = "ubuntu-2404"

  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "ubuntu-2404"
    vb.memory = 1024
    vb.cpus   = 1
    vb.gui    = false
  end

  config.vm.provider "vmware_desktop" do |vmware|
    vmware.vmx["displayName"] = "ubuntu-2404"
    vmware.vmx["memsize"]     = "1024"
    vmware.vmx["numvcpus"]    = "1"
    vmware.gui                = false
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -qq
    apt-get install -y --no-install-recommends curl git vim htop net-tools
    echo "Ubuntu 24.04 LTS ready. IP: 192.168.56.10"
  SHELL
end
